from __future__ import annotations

import re
from typing import Any

# Forbidden terms and their clean business-focused replacements
REPLACEMENTS = {
    r"\bideabee\b": "the company",
    r"\bagent workflow\b": "business process",
    r"\bagent workflows\b": "business processes",
    r"\bmulti-agent\b": "collaborative",
    r"\bagent\b": "advisor",
    r"\bagents\b": "advisors",
    r"\bpipeline\b": "process",
    r"\bchromadb\b": "database",
    r"\btavily\b": "search engine",
    r"\bopenrouter\b": "model platform",
    r"\blanggraph\b": "logic engine",
    r"\blangchain\b": "framework",
    r"\bprompts\b": "instructions",
    r"\bprompt\b": "instruction",
    r"\bsystem log\b": "activity log",
}

def clean_string(text: str, startup_name: str = "") -> str:
    if not isinstance(text, str):
        return text

    cleaned = text.strip()
    
    # Strip wrapping quotes
    if cleaned.startswith('"') and cleaned.endswith('"'):
        cleaned = cleaned[1:-1]
    elif cleaned.startswith("'") and cleaned.endswith("'"):
        cleaned = cleaned[1:-1]
        
    cleaned = cleaned.replace("\\n", "\n").replace('\\"', '"')

    # Apply replacement rules case-insensitively
    comp_name = startup_name.strip() if startup_name else "the company"

    # Remove footprint footers / platform leakage
    cleaned = re.sub(r"\bGenerated by\s+IdeaBee\s+AI\s+Startup\s+Builder\b\.?", "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"\bGenerated by\s+IdeaBee\b\.?", "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"\bAI\s+Startup\s+Builder\b\.?", "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"\b5-Agent\s+System\b\.?", "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"\b5-agent\s+optimized\s+system\b\.?", "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"\bAI\s+workflow\s+pipeline\b\.?", "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"\bResearch\s+agent\s+output\b\.?", "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"\bGenerated\s+by\s+agent\s+architecture\b\.?", "", cleaned, flags=re.IGNORECASE)
    
    # Replace IdeaBee with company name specifically (only if the startup name isn't actually IdeaBee)
    if comp_name.lower() != "ideabee":
        cleaned = re.sub(r"\bideabee\b", comp_name, cleaned, flags=re.IGNORECASE)
        cleaned = re.sub(r"\bIdeaBee\b", comp_name, cleaned)

    for pattern, replacement in REPLACEMENTS.items():
        if pattern == r"\bideabee\b":
            continue
        cleaned = re.sub(pattern, replacement, cleaned, flags=re.IGNORECASE)

    # Clean up any residual double spacing or empty paragraphs
    cleaned = re.sub(r"\s+\.\s*$", "", cleaned)
    cleaned = re.sub(r"\s{2,}", " ", cleaned).strip()
    return cleaned


def validate_and_sanitize(data: Any, startup_name: str = "") -> Any:
    if isinstance(data, str):
        return clean_string(data, startup_name)
    elif isinstance(data, dict):
        # We recursively clean keys and values
        new_dict = {}
        for k, v in data.items():
            new_key = clean_string(str(k), startup_name)
            new_dict[new_key] = validate_and_sanitize(v, startup_name)
        return new_dict
    elif isinstance(data, list):
        return [validate_and_sanitize(item, startup_name) for item in data]
    return data


def push_profile_version(history: list[dict[str, Any]], profile: dict[str, Any]) -> list[dict[str, Any]]:
    import copy
    copied = copy.deepcopy(profile)
    if history and history[-1] == copied:
        return history
    new_history = list(history)
    new_history.append(copied)
    if len(new_history) > 3:
        new_history.pop(0)
    return new_history

